Delete tick.json
[23:08:39 ERROR]: Couldn't read function tag list minecraft:tick from minecraft:tags/functions/tick.json in data pack pack.zip
com.google.gson.JsonSyntaxException: Missing values, expected to find a JsonArray
        at net.minecraft.server.v1_14_R1.ChatDeserializer.u(SourceFile:426) ~[patched_1.14.2.jar:git-Paper-81]
        at net.minecraft.server.v1_14_R1.Tag$a.a(SourceFile:135) ~[patched_1.14.2.jar:git-Paper-81]
        at net.minecraft.server.v1_14_R1.Tags.a(SourceFile:103) ~[patched_1.14.2.jar:git-Paper-81]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590) ~[?:1.8.0_212]
        at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1582) ~[?:1.8.0_212]
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) ~[?:1.8.0_212]
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) ~[?:1.8.0_212]
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692) ~[?:1.8.0_212]
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) ~[?:1.8.0_212]